config/routes.rb
Rails.application.routes.draw do
  resources :oeuvres

  root 'oeuvres#index'

end

app/models/oeuvre.rb
class Oeuvre < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/oeuvres_controller.rb
class OeuvresController < ApplicationController
  before_action :set_oeuvre, only: [:show, :edit, :update, :destroy]

  # GET /oeuvres
  # GET /oeuvres.json
  def index
    @oeuvres = Oeuvre.all
  end

  # GET /oeuvres/1
  # GET /oeuvres/1.json
  def show
  end

  # GET /oeuvres/new
  def new
    @oeuvre = Oeuvre.new
  end

  # GET /oeuvres/1/edit
  def edit
  end

  # POST /oeuvres
  # POST /oeuvres.json
  def create
    @oeuvre = Oeuvre.new(oeuvre_params)

    respond_to do |format|
      if @oeuvre.save
        format.html { redirect_to @oeuvre, notice: 'Oeuvre was successfully created.' }
        format.json { render :show, status: :created, location: @oeuvre }
      else
        format.html { render :new }
        format.json { render json: @oeuvre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oeuvres/1
  # PATCH/PUT /oeuvres/1.json
  def update
    respond_to do |format|
      if @oeuvre.update(oeuvre_params)
        format.html { redirect_to @oeuvre, notice: 'Oeuvre was successfully updated.' }
        format.json { render :show, status: :ok, location: @oeuvre }
      else
        format.html { render :edit }
        format.json { render json: @oeuvre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oeuvres/1
  # DELETE /oeuvres/1.json
  def destroy
    @oeuvre.destroy
    respond_to do |format|
      format.html { redirect_to oeuvres_url, notice: 'Oeuvre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oeuvre
      @oeuvre = Oeuvre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oeuvre_params
      params.require(:oeuvre).permit(:auteur, :titre, :forme, :date, :localisation, :descritpion, :critiques, :connexes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oeuvres_helper.rb
module OeuvresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="row navbar navbar-default navbar-fixed-top" id="header">
    <div class="col-md-4" id="websitename">
      <%= link_to "Recension", root_path%>
    </div>
    <div class="col-md-2" id="search">
      Rechercher
    </div>
      <div class="col-md-2" id="rank">
        Trier
      </div>
      <div class="col-md-2" id="create">
        <%= link_to 'Créer', new_oeuvre_path %>
      </div>

  </div>

<%= yield %>

</body>
</html>

app/views/oeuvres/_form.html.erb
<%= form_for(@oeuvre) do |f| %>
  <% if @oeuvre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oeuvre.errors.count, "error") %> prohibited this oeuvre from being saved:</h2>

      <ul>
      <% @oeuvre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auteur %><br>
    <%= f.text_field :auteur %>
  </div>
  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :forme %><br>
    <%= f.text_field :forme %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :localisation %><br>
    <%= f.text_field :localisation %>
  </div>
  <div class="field">
    <%= f.label :descritpion %><br>
    <%= f.text_area :descritpion %>
  </div>
  <div class="field">
    <%= f.label :critiques %><br>
    <%= f.text_area :critiques %>
  </div>
  <div class="field">
    <%= f.label :connexes %><br>
    <%= f.text_field :connexes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oeuvres/edit.html.erb
<h1>Editing Oeuvre</h1>

<%= render 'form' %>

<%= link_to 'Montrer', @oeuvre %> |
<%= link_to 'Retour', oeuvres_path %>

app/views/oeuvres/index.html.erb
<p id="notice"><%= notice %></p>

<header>
</header>

<body>

  <div id="firstscreen">

  </div>
  <div class="row" id="index">
    <% @oeuvres.each do |oeuvre| %>
      <div class="row" id="index-projects">
        <div class= "thumbnail" id="thumbnail">
          <div class="row center pad-top" id="thumb-author"><%= oeuvre.auteur %></div>
          <div class="row center" id="thumb-title"><%= link_to "#{oeuvre.titre}", oeuvre %></div>
          <div id="short_description" class="row center  pad-top" id="thumb-desc"><%= oeuvre.descritpion %></div>
         <div class="row center pad-top" id="thumb-forme"><%= oeuvre.forme %> - <%= oeuvre.date %></div>
        </div>
      </div>
    <% end %>
  </div>

</body>

<br>

app/views/oeuvres/new.html.erb
<div class="panel panel-default">

<div class="panel-heading">
	Nouvelle référence
</div>

<div class="panel-body"  id="panel-body">
<%= render 'form' %>
</div>
<%= link_to 'Retour', oeuvres_path %>
</div>

app/views/oeuvres/show.html.erb
<p id="notice"><%= notice %></p>

<div id="show">
  <div class="row">
  <div class="col-md-3" id="show-col-1">
    <div class="row">
        <p>
          <!--<strong>Auteur:</strong>-->
          <%= @oeuvre.auteur %>
        </p>
        <p id="thumb-title">
          <!--<strong>Titre:</strong>-->
          <%= @oeuvre.titre %>
        </p>
    </div>

    <div class="row">
      <p>
        <!--<strong>Forme:</strong>-->
        <%= @oeuvre.forme %> - <%= @oeuvre.date %>

      </p>

      <p>
        <strong>Localisation:</strong>
        <%= link_to "#{@oeuvre.localisation}", target: :_blank %>
      </p>
    </div>
  </div>
  <div class="col-md-8" id="show-desc">
  <p>
    <strong>Descritpion:</strong>
    <%= @oeuvre.descritpion %>
  </p>
  </div>
  <div class="col-md-1">
  </div>
  </div>

  <div class="row">
  <p>
    <strong>Critiques:</strong>
    <%= @oeuvre.critiques %>
  </p>
  </div>
  <div class="row">
  <p>
    <strong>Connexes:</strong>
    <%= @oeuvre.connexes %>
  </p>
  </div>
</div>


<%= link_to 'Éditer', edit_oeuvre_path(@oeuvre) %>
<%= link_to 'Supprimer', @oeuvre, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %>
<%= link_to 'Retour', oeuvres_path %>